### ISSUE TITLE
The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.

### ISSUE THREAD

**Issue by siraben** [dint-dev/universal_io#17]
Latest version of universal_io

```ShellSession
$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
lib/myapp/pages/profile/profile_image_edit_page.dart:148:76: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'package:universal_io/src/io/file.dart'
 ('/usr/local/Caskroom/flutter/1.22.6/flutter/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.0/lib/src/io/file.dart').
 - 'File/*2*/' is from 'dart:io'.
                    var storageUploadTask = await storageReference.putFile(profileImage);
                                                                           ^
lib/myapp/pages/profile/profile_image_edit_page.dart:215:57: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'package:universal_io/src/io/file.dart'
 ('/usr/local/Caskroom/flutter/1.22.6/flutter/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.0/lib/src/io/file.dart').
 - 'File/*2*/' is from 'dart:io'.
                          child: Image(image: FileImage(profileImage), fit: BoxFit.fitHeight),
```

**Comment by nikhilmufc7** [comment]
I am having the same issue with the latest version of flutter web!

**Comment by terrier989** [comment]
Thanks for the issue report! This is fixed in 2.0.2.

**Comment by jbryanh** [comment]
Joining the crowd here.  Anyone with workarounds?

**Comment by tgpsantos** [comment]
Any solution? I'm getting the same error

**Comment by ashishpipaliya** [comment]
Issue still exists.

package version `universal_io: ^2.0.4`

Flutter version `[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1645], locale en-IN)`

Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/layout/sidebar.dart:47:36: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'package:universal_io/src/io/file.dart' ('../../../flutter2.10/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/file.dart').
 - 'File/*2*/' is from 'dart:io'.
              encoder.addFile(File.fromRawPath(Uint8List.fromList('Hello'.codeUnits)));
                                   ^
Failed to compile application.

**Comment by jstdk** [comment]
Same issue here. It conflicts with local_auth package. 

Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'package:universal_io/src/io/file.dart'

**Comment by ichenwanbing** [comment]
: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
lib/…/widgets/image.dart:136
 - 'File/*1*/' is from 'dart:io'.
- 'File/*2*/' is from 'package:extended_image_library/src/_platform_web.dart' ('/C:/Users/H3C/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/extended_image_library-3.2.0/lib/src/_platform_web.dart').
package:extended_image_library/src/_platform_web.dart:1
          File(url),
          ^

Failed to compile application.
